version: '3.8'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: softy-pinko-front-end:task4
    ports:
      - "8080:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"
